alias: NINA Katastrophenalarm
description: ""
triggers:
  - trigger: time_pattern
    minutes: /5
conditions:
  - condition: or
    conditions:
      - condition: template
        value_template: >-
          {{state_attr("binary_sensor.nina_warning_steinfeld_main_spessart_bayern_1","severity")
          in ["Moderate","Severe","Extreme"]}}
      - condition: template
        value_template: >-
          {{state_attr("binary_sensor.nina_warning_steinfeld_main_spessart_bayern_2","severity")
          in ["Moderate","Severe","Extreme"]}}
      - condition: template
        value_template: >-
          {{state_attr("binary_sensor.nina_warning_steinfeld_main_spessart_bayern_3","severity")
          in ["Moderate","Severe","Extreme"]}}
actions:
  - action: open_epaper_link.setled
    target:
      device_id:
        - 11b1b5e9841630d32ba9f4025eb1be18
    data:
      mode: flash
      brightness: 8
      repeats: 100
      color1:
        - 255
        - 0
        - 0
      flashSpeed1: 0.5
      flashCount1: 2
      delay1: 0.1
      color2:
        - 255
        - 0
        - 0
      flashSpeed2: 0.5
      flashCount2: 2
      delay2: 0.1
      color3:
        - 255
        - 0
        - 0
      flashSpeed3: 0.5
      flashCount3: 2
      delay3: 0
mode: single
