alias: Bilderrahmen
description: ""
triggers:
  - trigger: time_pattern
    minutes: /29
conditions:
  - condition: time
    after: "06:00:00"
    before: "02:00:00"
  - condition: state
    entity_id: sensor.pixel_7_pro_wi_fi_connection
    state: Asgaard
actions:
  - action: shell_command.random_img_url
    metadata: {}
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - action: open_epaper_link.drawcustom
    data:
      ttl: 86400
      background: white
      dither: 1
      rotate: 0
      dry-run: false
      payload:
        - type: dlimg
          url: frame_temp/tempframe.jpg
          x: 0
          "y": 0
          resize_method: cover
          xsize: 960
          ysize: 768
    target:
      device_id: 90e9b26b29858cc7284e3540573ae9c0
mode: single
